In [1]:
import sys

print(sys.executable)

e:\Rag Course\CareerRAG\Project\CareerRAG\.venv\Scripts\python.exe

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

In [3]:
DATA_PATH = Path("../data/raw/jobs/nextgig_jobs.parquet")

df = pd.read_parquet(DATA_PATH)

print("Dataset loaded successfully!")
print(f"Shape: {df.shape}")

Dataset loaded successfully!
Shape: (112816, 47)

In [4]:
print("Number of columns:", len(df.columns))

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Number of columns: 47
1. title
2. normalized_title
3. company_name
4. ats_name
5. industry
6. function
7. occupational_category
8. employment_type
9. work_model
10. schedule
11. shift
12. experience_level
13. job_level_normalized
14. years_experience_numeric
15. education_level
16. skills_required
17. minimum_qualifications
18. preferred_qualifications
19. responsibilities
20. certifications
21. languages_required
22. salary_min
23. salary_max
24. salary_currency
25. salary_rate_unit
26. salary_type
27. pay_frequency
28. bonus
29. equity
30. on_target_earnings
31. benefits
32. city
33. country
34. location_resolved
35. locations
36. remote_eligibility_regions
37. latitude
38. longitude
39. visa_sponsorship_available
40. work_authorization_requirements
41. security_clearance
42. relocation_assistance
43. travel_required
44. travel_percentage
45. date_posted
46. closing_date
47. job_description

In [5]:
pd.set_option("display.max_columns", None)

df.head(3)

,title,normalized_title,company_name,ats_name,industry,function,occupational_category,employment_type,work_model,schedule,shift,experience_level,job_level_normalized,years_experience_numeric,education_level,skills_required,minimum_qualifications,preferred_qualifications,responsibilities,certifications,languages_required,salary_min,salary_max,salary_currency,salary_rate_unit,salary_type,pay_frequency,bonus,equity,on_target_earnings,benefits,city,country,location_resolved,locations,remote_eligibility_regions,latitude,longitude,visa_sponsorship_available,work_authorization_requirements,security_clearance,relocation_assistance,travel_required,travel_percentage,date_posted,closing_date,job_description
0,Implementation Manager,Implementation Manager,North American Bancard,Workday,NaN,NaN,NaN,Full-time,Remote,NaN,NaN,Mid,Mid,NaN,NaN,"[""Project Management"", ""Payment Processing"", ""...","[""4+ years implementation in merchant payment ...",NaN,"[""Primary point of contact for merchant implem...",NaN,NaN,67000.0,77000.00,USD,year,NaN,NaN,"Medical Dental Vision,Flexible PTO,401k Match,...",NaN,NaN,"[""Medical Dental Vision"", ""Flexible PTO"", ""401...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,0.0,NaN,NaN,PayTrace by North - Merchant Operations team t...
1,Personal Shopper Part Time Day,Personal Shopper Part Time Day,LOBLAW,Workday,NaN,NaN,NaN,Part-time,On-site,NaN,NaN,Entry,Entry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saskatoon,Canada,"Saskatoon,SK,Canada","[""Saskatoon,SK,Canada""]",NaN,52.131802,-106.660767,NaN,NaN,NaN,False,False,0.0,NaN,NaN,Your Independent Grocer team delivers personal...
2,Cashier Part Time Day,Cashier Part Time Day,LOBLAW,Workday,NaN,NaN,NaN,Part-time,On-site,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.9,20.55,USD,hour,NaN,NaN,NaN,NaN,NaN,NaN,Hampton,Canada,"Hampton,NB,Canada","[""Hampton,NB,Canada""]",NaN,45.475176,-65.824808,NaN,NaN,NaN,False,False,0.0,NaN,NaN,Your Independent Grocer team connects with cus...

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112816 entries, 0 to 112815
Data columns (total 47 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   title                            112816 non-null  str
 1   normalized_title                 112815 non-null  str
 2   company_name                     112816 non-null  str
 3   ats_name                         104263 non-null  str
 4   industry                         7358 non-null    str
 5   function                         7682 non-null    str
 6   occupational_category            2183 non-null    str
 7   employment_type                  111344 non-null  str
 8   work_model                       87117 non-null   str
 9   schedule                         33157 non-null   str
 10  shift                            13381 non-null   str
 11  experience_level                 65095 non-null   str
 12  job_level_normalized             57410 non-null   str
 13  years_experience_numeric         245 non-null     float64
 14  education_level                  10087 non-null   str
 15  skills_required                  80412 non-null   str
 16  minimum_qualifications           87906 non-null   str
 17  preferred_qualifications         28480 non-null   str
 18  responsibilities                 90771 non-null   str
 19  certifications                   6564 non-null    str
 20  languages_required               8079 non-null    str
 21  salary_min                       51829 non-null   float64
 22  salary_max                       47162 non-null   float64
 23  salary_currency                  53909 non-null   str
 24  salary_rate_unit                 52307 non-null   str
 25  salary_type                      3343 non-null    str
 26  pay_frequency                    765 non-null     str
 27  bonus                            5585 non-null    str
 28  equity                           2138 non-null    str
 29  on_target_earnings               1212 non-null    str
 30  benefits                         73485 non-null   str
 31  city                             106582 non-null  str
 32  country                          103467 non-null  str
 33  location_resolved                106582 non-null  str
 34  locations                        106815 non-null  str
 35  remote_eligibility_regions       36060 non-null   str
 36  latitude                         106582 non-null  float64
 37  longitude                        106582 non-null  float64
 38  visa_sponsorship_available       4492 non-null    str
 39  work_authorization_requirements  1271 non-null    str
 40  security_clearance               2144 non-null    str
 41  relocation_assistance            108615 non-null  str
 42  travel_required                  108777 non-null  str
 43  travel_percentage                107803 non-null  float64
 44  date_posted                      21828 non-null   str
 45  closing_date                     16658 non-null   str
 46  job_description                  112816 non-null  str
dtypes: float64(6), str(41)
memory usage: 175.9 MB

In [7]:
df.isnull().sum()

title                                   0
normalized_title                        1
company_name                            0
ats_name                             8553
industry                           105458
function                           105134
occupational_category              110633
employment_type                      1472
work_model                          25699
schedule                            79659
shift                               99435
experience_level                    47721
job_level_normalized                55406
years_experience_numeric           112571
education_level                    102729
skills_required                     32404
minimum_qualifications              24910
preferred_qualifications            84336
responsibilities                    22045
certifications                     106252
languages_required                 104737
salary_min                          60987
salary_max                          65654
salary_currency                     58907
salary_rate_unit                    60509
salary_type                        109473
pay_frequency                      112051
bonus                              107231
equity                             110678
on_target_earnings                 111604
benefits                            39331
city                                 6234
country                              9349
location_resolved                    6234
locations                            6001
remote_eligibility_regions          76756
latitude                             6234
longitude                            6234
visa_sponsorship_available         108324
work_authorization_requirements    111545
security_clearance                 110672
relocation_assistance                4201
travel_required                      4039
travel_percentage                    5013
date_posted                         90988
closing_date                        96158
job_description                         0
dtype: int64

In [8]:
missing = df.isnull().sum().sort_values(ascending=False)

missing_percentage = (
    df.isnull().mean() * 100
).sort_values(ascending=False)

missing_df = pd.DataFrame({
    "missing_count": missing,
    "missing_percentage": missing_percentage
})

missing_df

                                 missing_count  missing_percentage
years_experience_numeric                112571           99.782832
pay_frequency                           112051           99.321905
on_target_earnings                      111604           98.925684
work_authorization_requirements         111545           98.873387
equity                                  110678           98.104879
security_clearance                      110672           98.099560
occupational_category                   110633           98.064991
salary_type                             109473           97.036768
visa_sponsorship_available              108324           96.018295
bonus                                   107231           95.049461
certifications                          106252           94.181676
industry                                105458           93.477875
function                                105134           93.190682
languages_required                      104737           92.838782
education_level                         102729           91.058892
shift                                    99435           88.139094
closing_date                             96158           85.234364
date_posted                              90988           80.651681
preferred_qualifications                 84336           74.755354
schedule                                 79659           70.609665
remote_eligibility_regions               76756           68.036449
salary_max                               65654           58.195646
salary_min                               60987           54.058821
salary_rate_unit                         60509           53.635123
salary_currency                          58907           52.215111
job_level_normalized                     55406           49.111828
experience_level                         47721           42.299851
benefits                                 39331           34.862963
skills_required                          32404           28.722876
work_model                               25699           22.779570
minimum_qualifications                   24910           22.080201
responsibilities                         22045           19.540668
country                                   9349            8.286945
ats_name                                  8553            7.581371
city                                      6234            5.525812
location_resolved                         6234            5.525812
longitude                                 6234            5.525812
latitude                                  6234            5.525812
locations                                 6001            5.319281
travel_percentage                         5013            4.443519
relocation_assistance                     4201            3.723763
travel_required                           4039            3.580166
employment_type                           1472            1.304779
normalized_title                             1            0.000886
title                                        0            0.000000
company_name                                 0            0.000000
job_description                              0            0.000000

In [9]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [10]:
job = df.iloc[0]

job

title                                                         Implementation Manager
normalized_title                                              Implementation Manager
company_name                                                  North American Bancard
ats_name                                                                     Workday
industry                                                                         NaN
function                                                                         NaN
occupational_category                                                            NaN
employment_type                                                            Full-time
work_model                                                                    Remote
schedule                                                                         NaN
shift                                                                            NaN
experience_level                                                                 Mid
job_level_normalized                                                             Mid
years_experience_numeric                                                         NaN
education_level                                                                  NaN
skills_required                    ["Project Management", "Payment Processing", "...
minimum_qualifications             ["4+ years implementation in merchant payment ...
preferred_qualifications                                                         NaN
responsibilities                   ["Primary point of contact for merchant implem...
certifications                                                                   NaN
languages_required                                                               NaN
salary_min                                                                   67000.0
salary_max                                                                   77000.0
salary_currency                                                                  USD
salary_rate_unit                                                                year
salary_type                                                                      NaN
pay_frequency                                                                    NaN
bonus                              Medical Dental Vision,Flexible PTO,401k Match,...
equity                                                                           NaN
on_target_earnings                                                               NaN
benefits                           ["Medical Dental Vision", "Flexible PTO", "401...
city                                                                             NaN
country                                                                          NaN
location_resolved                                                                NaN
locations                                                                        NaN
remote_eligibility_regions                                                       NaN
latitude                                                                         NaN
longitude                                                                        NaN
visa_sponsorship_available                                                       NaN
work_authorization_requirements                                                  NaN
security_clearance                                                               NaN
relocation_assistance                                                          False
travel_required                                                                False
travel_percentage                                                                0.0
date_posted                                                                      NaN
closing_date                                                                     NaN
job_description                    PayTrace by North - Merchant Operations team t...
Name: 0, dtype: object

In [11]:
print(df["job_description"].iloc[0])

PayTrace by North - Merchant Operations team transforms B2B payments through advanced gateway solutions. The Implementation Manager oversees end-to-end onboarding for new merchants, guiding them through PayTrace platform, ISV and ERP integrations, and ensuring smooth go-live and transition to Client Services. Remote US, work hours start 9-10 am Eastern, travel up to 10%.

In [12]:
print(df["skills_required"].iloc[0])

["Project Management", "Payment Processing", "Merchant Onboarding", "ISV Integration", "ERP Integration", "Compliance Review", "Customer Communication", "Remote Collaboration"]